#!/usr/bin/env python3
"""Write the publication data the page reads, in both of the forms it needs.

data/site-data.js is what the browser loads and the rail renders from. Keeping it
out of index.html matters: the JSON is tens of thousands of characters on one line,
and inlining it made index.html painful to open and edit by hand. A plain
<script src> is used rather than fetch() so the page still works from file://.

index.html also gets the same papers written into it as a plain numbered list,
between the PUBLICATION-FALLBACK markers inside #pubList. The script overwrites
that node the moment it runs, so nobody with JavaScript ever sees it — but it means
the papers are real text in the served HTML for anything that does not run scripts:
search crawlers on their first pass, Bing, answer engines, reader modes, and anyone
browsing with JavaScript off. It is the same content the rail shows, not a
crawler-only variant.

    python3 scripts/embed_publications.py
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from refresh_publications import CO_FIRST   # noqa: E402  (one source of truth)

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "site-data.js"


def slug(doi):
    return re.sub(r"[^a-z0-9]+", "-", doi.lower()).strip("-")


def load(name):
    path = ROOT / "data" / name
    return json.loads(path.read_text()) if path.exists() else []


pubs = load("publications.json")
preprints = load("preprints.json")

# Mark which papers have a rendered first page, so the browser requests only images
# that exist. Probing and letting them 404 works, but fills the console with errors.
for pub in pubs + preprints:
    pub["page"] = (ROOT / "images" / "pubs" / f"{slug(pub['doi'])}.jpg").exists()
    # Stamped here as well as in refresh_publications.py so that adding a paper to
    # CO_FIRST takes effect on the next build, without a network refresh.
    pub["shared"] = CO_FIRST.get(pub["doi"], 0)

# Preprint servers aren't named in Crossref's container-title, so derive a label.
SERVERS = {"10.1101": "bioRxiv / medRxiv", "10.64898": "bioRxiv / medRxiv",
           "10.21203": "Research Square"}
for pub in preprints:
    pub["server"] = next((v for k, v in SERVERS.items() if pub["doi"].startswith(k)), "Preprint")

# A preprint with no first page has no PDF behind it; leave it off the site rather
# than showing a bare title tile.
dropped = [p for p in preprints if not p["page"]]
preprints = [p for p in preprints if p["page"]]
for p in dropped:
    print(f"  preprint without a PDF, not listed: {p['title'][:52]}")

payload = json.dumps({"publications": pubs, "preprints": preprints}, indent=1)
OUT.write_text(
    "// Generated by scripts/embed_publications.py — do not edit by hand.\n"
    "// Regenerate with: python3 scripts/refresh_publications.py && python3 scripts/embed_publications.py\n"
    "window.SITE_DATA = " + payload + ";\n"
)

with_page = sum(1 for p in pubs + preprints if p["page"])
print(f"wrote {OUT.relative_to(ROOT)} — {len(pubs)} publications + {len(preprints)} preprints, "
      f"{with_page} with a first page")


# ----------------------------------------------------------------------------
# The no-JavaScript copy of the same list, written into index.html.
# ----------------------------------------------------------------------------

SELF = re.compile(r"^Hamilton(\s+Se[- ]?Hwee)?\s+Oh$", re.I)
SELF_AS = "Oh HS"
# Consortium and collaboration bylines are single names, not people; abbreviating
# them to "Initiative T" would be nonsense, so they are kept whole.
GROUP = re.compile(r"consorti|collaborat|network|initiative|investigator|study group"
                   r"|\bgroup\b|working party", re.I)


def escape(text):
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
                     .replace(">", "&gt;").replace('"', "&quot;"))


# Surname particles. Taking only the last word as the family name turns "Yann Le Guen"
# into "Guen YL" and "Sven J. van der Lee" into "Lee SJVD". Keep in step with PARTICLE
# in index.html.
PARTICLE = {"de", "del", "della", "der", "di", "do", "dos", "da", "das", "du", "la",
            "le", "van", "von", "ter", "ten", "af", "av", "bin", "ibn", "al", "el"}


def initials(name):
    """Mirror of initials() in index.html, so both lists read identically."""
    name = name.strip()
    if SELF.match(name):
        return SELF_AS
    if GROUP.search(name):
        return escape(name)
    parts = name.split()
    if len(parts) < 2:
        return escape(name)
    family = parts.pop()
    # Stop at one remaining word so a name that is all particles still has a given name.
    while len(parts) > 1 and parts[-1].lower() in PARTICLE:
        family = f"{parts.pop()} {family}"
    given = "".join(piece[0] for part in parts for piece in part.split("-") if piece)
    return escape(f"{family} {given.upper()}")


def author_line(pub):
    """Mirror of authorLine(): long lists collapse to first three, self, and last."""
    names = pub.get("authors") or []
    if not names:
        return ""
    if len(names) <= 8:
        keep = list(range(len(names)))
    else:
        keep = [0, 1, 2]
        if pub.get("pos"):
            keep.append(pub["pos"] - 1)
        keep.append(len(names) - 1)
        keep = sorted({i for i in keep if 0 <= i < len(names)})

    shared = pub.get("shared") or 0
    out, previous = "", -1
    for slot, i in enumerate(keep):
        if slot:
            out += ", " if i == previous + 1 else ", … "
        mark = initials(names[i])
        if i < shared:
            mark += "*"          # journal convention for equal contribution
        out += f"<b>{mark}</b>" if pub.get("pos") == i + 1 else mark
        previous = i
    return out


def fallback_list(items):
    rows = []
    for pub in items:
        venue = pub.get("server") if pub.get("preprint") else pub.get("journal")
        bits = [b for b in (escape(venue), str(pub.get("year") or "")) if b]
        if pub.get("shared"):
            bits.append("(* equal contribution)")
        rows.append(
            "        <li>"
            f'<cite><a href="https://doi.org/{escape(pub["doi"])}">'
            f'{escape(pub["title"])}</a></cite>. '
            f'{author_line(pub)}. <em>{" ".join(bits)}</em>.'
            "</li>"
        )
    return rows


INDEX = ROOT / "index.html"
OPEN = ("      <!-- PUBLICATION-FALLBACK: written by scripts/embed_publications.py. "
        "Do not hand-edit;\n           your changes are overwritten on the next build. -->")
CLOSE = "      <!-- /PUBLICATION-FALLBACK -->"

html = INDEX.read_text()
start, end = html.find(OPEN), html.find(CLOSE)
if start == -1 or end == -1 or end < start:
    raise SystemExit(
        "could not find the PUBLICATION-FALLBACK markers in index.html.\n"
        "They live inside <div class=\"pub-rail\" id=\"pubList\">; restore them and re-run."
    )

block = "\n".join(
    [OPEN, '      <ol class="pub-fallback">']
    + fallback_list(pubs) + fallback_list(preprints)
    + ["      </ol>", ""]
)
INDEX.write_text(html[:start] + block + html[end:])
print(f"wrote the no-JavaScript list into index.html — {len(pubs) + len(preprints)} papers")
